import { useCallback, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { referenciaService, cadastroService } from "../services";
import { errorMessage } from "../services/api";
import { useQuery } from "../hooks/useQuery";
import { Button, Card, EmptyState, ErrorState, Field, Loading, PageHeader, Pagination, useToast } from "../components/ui";
import { date } from "../utils/format";
function status(open:string,close:string){const now=Date.now();return now<new Date(open).getTime()?"Não iniciado":now<=new Date(close).getTime()?"Aberto":"Encerrado"}
export function PeriodManagement(){
 const [year,setYear]=useState(new Date().getFullYear()),[busy,setBusy]=useState(false);const toast=useToast();
 const query=useQuery(useCallback(async(signal:AbortSignal)=>{const [years,periods]=await Promise.all([referenciaService.years(signal),cadastroService.all("bimestres",signal)]);return{years,periods}},[]));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await referenciaService.createYear(year);toast("Ano letivo criado com os quatro bimestres.");query.reload()}catch(e){toast(errorMessage(e),true)}finally{setBusy(false)}}
 return <><PageHeader title="Bimestres" description="Cada ano letivo possui exatamente quatro períodos de lançamento."/><Card className="form-card"><form className="filters" onSubmit={submit}><Field label="Novo ano letivo"><input type="number" min={2000} max={2100} value={year} onChange={e=>setYear(Number(e.target.value))} required/></Field><Button disabled={busy}>{busy?"Criando…":"Criar quatro bimestres"}</Button></form></Card>
 {query.loading?<Loading/>:query.error?<ErrorState error={query.error} retry={query.reload}/>:!query.data?.years.length?<Card><EmptyState title="Nenhum ano letivo cadastrado"/></Card>:query.data.years.map(y=><Card className="table-wrap mt" key={y.ano}><div className="table-toolbar"><div><h2>{y.ano}</h2><p>{y.totalBimestres} de 4 bimestres configurados</p></div></div><div className="table-scroll"><table><thead><tr><th>Período</th><th>Abertura</th><th>Encerramento</th><th>Status</th><th>Ação</th></tr></thead><tbody>{query.data!.periods.filter(p=>p.anoLetivo===y.ano).sort((a,b)=>a.numero-b.numero).map(p=><tr key={p.id}><td><strong>{p.numero}º bimestre</strong></td><td>{date(p.dataHoraAbertura)}</td><td>{date(p.dataHoraEncerramento)}</td><td><span className={`simple-badge ${status(p.dataHoraAbertura,p.dataHoraEncerramento)==="Aberto"?"success":""}`}>{status(p.dataHoraAbertura,p.dataHoraEncerramento)}</span></td><td><Link className="text-link" to={`/bimestres/${p.id}/editar`}>Editar datas</Link></td></tr>)}</tbody></table></div></Card>)}</>
}
const actions:Record<string,string>={GET:"Consulta",POST:"Criação",PUT:"Alteração",PATCH:"Mudança de estado",DELETE:"Inativação"};
export function Audit(){const[page,setPage]=useState(0);const query=useQuery(useCallback((s:AbortSignal)=>referenciaService.audit(page,s),[page]));return <><PageHeader title="Auditoria" description="Rastreabilidade das ações realizadas na plataforma."/><Card className="table-wrap">{query.loading?<Loading/>:query.error?<ErrorState error={query.error} retry={query.reload}/>:!query.data?.content.length?<EmptyState title="Nenhum evento de auditoria"/>:<><div className="table-scroll"><table><thead><tr><th>Autor</th><th>Ação</th><th>Data e hora</th><th>Recurso</th><th>Resultado</th></tr></thead><tbody>{query.data.content.map(i=><tr key={i.id}><td>{i.usuario}</td><td>{actions[i.metodo]||i.metodo}</td><td>{new Date(i.dataHora).toLocaleString("pt-BR")}</td><td>{i.recurso}</td><td>{i.status>=200&&i.status<300?"Concluído":"Não concluído"}</td></tr>)}</tbody></table></div><Pagination page={query.data} onChange={setPage}/></>}</Card></>}
