import { useCallback } from "react";
import { Link } from "react-router-dom";
import { cadastroService } from "../services";
import { useQuery } from "../hooks/useQuery";
import type { Vinculo } from "../types";
import { Card, EmptyState, ErrorState, Loading, PageHeader } from "../components/ui";
function useLinks(){return useQuery(useCallback((s:AbortSignal)=>cadastroService.all("vinculos",s),[]))}
export function MyClasses(){const q=useLinks();const groups=Object.values((q.data||[]).filter(v=>v.ativo).reduce<Record<number,{turma:Vinculo["turma"];links:Vinculo[]}>>((a,v)=>{(a[v.turma.id]??={turma:v.turma,links:[]}).links.push(v);return a},{}));return <><PageHeader title="Minhas turmas" description="Turmas vinculadas à sua atuação docente."/><Card>{q.loading?<Loading/>:q.error?<ErrorState error={q.error} retry={q.reload}/>:!groups.length?<EmptyState title="Nenhuma turma vinculada"/>:<div className="card-grid">{groups.map(g=><article className="resource-card" key={g.turma.id}><h2>{g.turma.nome}</h2><p>{g.turma.serie} · {g.turma.anoLetivo}</p><p><strong>Disciplinas:</strong> {[...new Set(g.links.map(v=>v.disciplina.nome))].join(", ")}</p><Link className="text-link" to={`/minhas-turmas/${g.turma.id}`}>Ver alunos</Link></article>)}</div>}</Card></>}
export function MyClassDetail(){const id=Number(location.pathname.split("/").pop());const links=useLinks();const students=useQuery(useCallback((s:AbortSignal)=>cadastroService.all("matriculas",s),[]));const allowed=links.data?.some(v=>v.ativo&&v.turma.id===id);if(links.loading||students.loading)return <Loading/>;if(links.error||students.error)return <ErrorState error={links.error||students.error||"Erro ao carregar"}/>;if(!allowed)return <AccessDenied/>;const turma=links.data!.find(v=>v.turma.id===id)!.turma;const rows=students.data!.filter(m=>m.ativo&&m.turma.id===id);return <><PageHeader title={turma.nome} description={`${turma.serie} · ${turma.anoLetivo}`}/><Card>{!rows.length?<EmptyState title="Nenhum aluno matriculado"/>:<div className="card-grid">{rows.map(m=><article className="resource-card" key={m.id}><h2>{m.aluno.nome}</h2><Link className="text-link" to={`/relatorios?alunoId=${m.aluno.id}`}>Ver acompanhamentos</Link></article>)}</div>}</Card></>}
export function MySubjects(){const q=useLinks();const unique=[...new Map((q.data||[]).filter(v=>v.ativo).map(v=>[v.disciplina.id,v.disciplina])).values()];return <><PageHeader title="Minhas disciplinas" description="Disciplinas dos seus vínculos ativos."/><Card>{q.loading?<Loading/>:q.error?<ErrorState error={q.error} retry={q.reload}/>:!unique.length?<EmptyState title="Nenhuma disciplina vinculada"/>:<div className="card-grid">{unique.map(d=><article className="resource-card" key={d.id}><h2>{d.nome}</h2><p>{d.areaDisciplina.nome}</p></article>)}</div>}</Card></>}
export function MyStudents(){const q=useQuery(useCallback((s:AbortSignal)=>cadastroService.all("alunos",s),[]));return <><PageHeader title="Meus alunos" description="Alunos vinculados à sua conta de responsável."/><Card>{q.loading?<Loading/>:q.error?<ErrorState error={q.error} retry={q.reload}/>:!q.data?.length?<EmptyState title="Nenhum aluno vinculado"/>:<div className="card-grid">{q.data.filter(a=>a.ativo).map(a=><article className="resource-card" key={a.id}><h2>{a.nome}</h2><Link className="text-link" to={`/relatorios?alunoId=${a.id}`}>Ver relatórios publicados</Link></article>)}</div>}</Card></>}
export function AccessDenied(){return <Card><EmptyState title="Acesso negado" description="Você não possui permissão para acessar esta página."><Link className="button primary" to="/dashboard">Voltar ao início</Link></EmptyState></Card>}
export function NotFound(){return <Card><EmptyState title="Página não encontrada" description="A página que você tentou acessar não existe ou foi movida."><Link className="button primary" to="/dashboard">Voltar ao início</Link></EmptyState></Card>}
