package br.com.kfka.service;
import br.com.kfka.model.*; import br.com.kfka.repository.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service @Transactional public class RecuperacaoSenhaService {
 private final UsuarioRepository usuarios; private final RecuperacaoSenhaTokenRepository tokens; private final PasswordEncoder encoder; private final Clock clock; private final boolean expor; private final SecureRandom random=new SecureRandom();
 public RecuperacaoSenhaService(UsuarioRepository u,RecuperacaoSenhaTokenRepository t,PasswordEncoder e,Clock c,@Value("${kfka.recuperacao.expor-codigo:false}") boolean x){usuarios=u;tokens=t;encoder=e;clock=c;expor=x;}
 public RecuperacaoSenhaResposta solicitar(String email){String codigo=null;var usuario=usuarios.findByEmail(email.trim().toLowerCase(Locale.ROOT)).filter(Usuario::getAtivo).orElse(null);if(usuario!=null){tokens.deleteAllByUsuario(usuario);byte[] bytes=new byte[32];random.nextBytes(bytes);codigo=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);var token=new RecuperacaoSenhaToken();token.setUsuario(usuario);token.setTokenHash(hash(codigo));token.setExpiraEm(LocalDateTime.now(clock).plusMinutes(15));tokens.saveAndFlush(token);}return new RecuperacaoSenhaResposta("Se o e-mail estiver cadastrado, use as instruções de recuperação.",expor?codigo:null);}
 public void redefinir(RedefinicaoSenha d){var token=tokens.findByTokenHash(hash(d.codigo())).orElseThrow(this::invalido);var agora=LocalDateTime.now(clock);if(token.getUsadoEm()!=null||!token.getExpiraEm().isAfter(agora))throw invalido();if(d.novaSenha().getBytes(StandardCharsets.UTF_8).length>72)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Senha deve ter até 72 bytes UTF-8");token.getUsuario().setSenha(encoder.encode(d.novaSenha()));token.setUsadoEm(agora);tokens.saveAndFlush(token);}
 private ResponseStatusException invalido(){return new ResponseStatusException(HttpStatus.BAD_REQUEST,"Código inválido ou expirado");}
 private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
